# Generated by Django 3.0.4 on 2020-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='signature',
            field=models.CharField(max_length=50),
        ),
    ]
